/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_justcode_hxl_androidstudydemo_ndkdemo_JNIUtil */

#ifndef _Included_com_justcode_hxl_androidstudydemo_ndkdemo_JNIUtil
#define _Included_com_justcode_hxl_androidstudydemo_ndkdemo_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_justcode_hxl_androidstudydemo_ndkdemo_JNIUtil
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_justcode_hxl_androidstudydemo_ndkdemo_JNIUtil_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
